name: Update Data

on:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch data from https://c26.sub-v2.workers.dev/frag
        run: curl -o custom.txt https://c26.sub-v2.workers.dev/frag
      
      - name: Fetch data from https://c26.sub-v2.workers.dev/sub
        run: curl -o normal.txt https://c26.sub-v2.workers.dev/sub
      
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add custom.txt normal.txt
          git commit -m "Update data files"
          git push
          
